[package]
name = "block-analyzer"
version = "0.1.0"
edition = "2021"

[dependencies]
bitcoinkernel = "0.0.13"
clap = { version = "4.5", features = ["derive"] }
env_logger = "0.11.6"
hex = "0.4.3"
log = "0.4.25"
rayon = "1.10.0"
